### ISSUE TITLE
error in CIS

### ISSUE THREAD

**Issue by radoslawpiwowarski** [niedoida/niedoida#49]
How to stop program run:
- small basis set (e.g. sto-3g)
- large number of excited states to calculate (e.g. 20)

Exemplary input:
```
td:
  type: tda
  no_states: 20
units:
  length: angstrom
title: test CIS
basis_set: sto-3g
atoms:
  - H 0.892435 -0.769423 0.454517
  - O 0.742719 0.058252 -0.028638
  - O -0.742719 -0.058252 -0.028638
  - H -0.892435 0.769424 0.454516
```
Actual result:
`error: Mat::cols(): indices out of bounds or incorrectly used
`
Excepted results:
No error  is thrown.
